#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd com.ingeint.bankloan.targetplatform
./plugin-builder $DEBUG_MODE ../com.ingeint.bankloan ../com.ingeint.bankloan.test
